'use strict';
// Real app routes/services and frontend replay client. No auth/Storage mocks.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto'),cp=require('node:child_process'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../../..'),target=JSON.parse(process.env.WORKFLOW_SERVICES_TARGET||'null');
if(!target||!/^[0-9a-f]{32}$/.test(target.run)||!target.network.startsWith('workflow_services_test_')||!target.database.startsWith('workflow_services_'))throw Error('Owned target missing');
function verify(){const c=JSON.parse(cp.execFileSync('docker',['inspect',target.db],{encoding:'utf8'}))[0];assert.equal(c.Config.Labels['codex.workflow.services'],target.run);assert.equal(c.Name,'/'+target.network+'_db');assert.equal(c.Config.Image,'postgres:16-alpine');assert.deepEqual(Object.keys(c.NetworkSettings.Networks),[target.network]);assert(c.Mounts.every(x=>x.Type==='tmpfs'));}
function sql(text){verify();const r=cp.spawnSync('docker',['exec','-i',target.db,'psql','-X','-qAt','-U','postgres','-d',target.database,'-v','ON_ERROR_STOP=1','-v','VERBOSITY=sqlstate','-f','-'],{input:text,encoding:'utf8'});if(r.status)throw Error('Test SQL failed SQLSTATE='+((r.stderr.match(/ERROR:\s+([A-Z0-9]{5})/)||[])[1]||'unknown'));return r.stdout.trim();}
const q=s=>"'"+String(s).replaceAll("'","''")+"'";
const output=path.join(root,'docs/auth-storage-integration/results.json'),results=[],counts={api:{},services:{},storageErrors:[],storageSign:0,refresh:0};
const record=(name,status,evidence)=>{results.push({name,status,evidence});process.stdout.write(JSON.stringify(results.at(-1))+'\n');};
const nativeFetch=globalThis.fetch;const origins=new Set(Object.values(target.ports).map(p=>'http://127.0.0.1:'+p));
globalThis.fetch=(input,options)=>{const u=new URL(typeof input==='string'?input:input.url||input.toString());if(!origins.has(u.origin))throw Error('Non-owned network target blocked');return nativeFetch(input,options);};
console.error=()=>{}; // Never print raw application/provider exceptions or URLs.
require(path.join(root,'backend/node_modules/ts-node/register/transpile-only'));
const Module=require('node:module'),resolve=Module._resolveFilename;
Module._resolveFilename=function(request,parent,...args){return resolve.call(this,request.startsWith('@/')?path.join(root,'frontend/src',request.slice(2)):request,parent,...args);};
let gateway,server;
const actors={},tokens={},pid=crypto.randomUUID(),mid=crypto.randomUUID(),otherMid=crypto.randomUUID(),oid=crypto.randomUUID();
const bytes=Buffer.from('%PDF-1.4\nSynthetic isolated service integration bytes\n%%EOF\n');
async function main(){
 verify();
 gateway=http.createServer((req,res)=>{const prefix=['auth','rest','storage'].find(k=>req.url.startsWith('/'+k+'/v1/'));if(!prefix){res.writeHead(404);res.end();return;}if(prefix==='storage'&&req.url.includes('/object/sign/'))counts.storageSign++;
 const proxy=http.request({host:'127.0.0.1',port:target.ports[prefix],path:req.url.slice(('/'+prefix+'/v1').length),method:req.method,headers:{...req.headers,host:'127.0.0.1:'+target.ports[prefix]}},r=>{const key=prefix+' '+req.method+' '+r.statusCode;counts.services[key]=(counts.services[key]||0)+1;
 if(prefix==='storage'&&r.statusCode>=400){let body='';r.on('data',b=>{if(body.length<8192)body+=b;});r.on('end',()=>{try{const e=JSON.parse(body);const safe={status:r.statusCode};for(const k of ['code','error','statusCode'])if(/^[A-Za-z0-9_ -]{1,60}$/.test(String(e[k]||'')))safe[k]=e[k];const known=['Bucket not found','Invalid JWT','jwt malformed','invalid signature','Invalid Compact JWS','signature verification failed','Unauthorized','The resource was not found','crypto is not defined','Invalid key','Access denied: Invalid role','JWT payload is missing','permission denied','new row violates row-level security policy'];safe.message=known.find(v=>String(e.message||'').includes(v))||'provider message omitted';counts.storageErrors.push(safe);}catch{counts.storageErrors.push({status:r.statusCode,message:'provider body omitted'});}});}
 res.writeHead(r.statusCode,r.headers);r.pipe(res);});proxy.on('error',()=>{res.writeHead(502);res.end('Local service unavailable');});req.pipe(proxy);});
 await new Promise(r=>gateway.listen(target.ports.gateway,'127.0.0.1',r));
 const config=require(path.join(root,'backend/src/config/supabase.ts'));
 const express=require(path.join(root,'backend/node_modules/express'));
 const wrapper=express();wrapper.use((req,res,next)=>{const p=req.path;counts.api[p]=(counts.api[p]||0)+1;if(p==='/api/auth/refresh')counts.refresh++;next();});wrapper.use(require(path.join(root,'backend/src/app.ts')).default);
 server=wrapper.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const api='http://127.0.0.1:'+server.address().port+'/api';origins.add(new URL(api).origin);
 const request=async(p,role,options={})=>{const headers=new Headers(options.headers);if(role)headers.set('Authorization','Bearer '+tokens[role].accessToken);if(typeof options.body==='string')headers.set('Content-Type','application/json');const r=await fetch(api+p,{...options,headers});const json=await r.json();return {status:r.status,json};};
 const login=async role=>{const r=await request('/auth/login',null,{method:'POST',body:JSON.stringify({email:actors[role].email,password:actors[role].password})});assert.equal(r.status,200,'Synthetic login HTTP');assert(r.json.data.accessToken&&r.json.data.refreshToken);tokens[role]=r.json.data;return r.json.data;};
 try{
  const bucket=await config.supabaseAdmin.storage.getBucket('workflow-documents');assert(!bucket.error,'Real Storage bucket access code='+bucket.error?.name+' status='+bucket.error?.status);assert.equal(bucket.data.public,false);
  for(const [key,role,active] of [['sales','SALES',true],['pic','SA',true],['head','HEAD_SA',true],['outsider','SA',true],['inactive','SA',false]]){
   const email='fixture-'+key+'-'+target.run.slice(0,8)+'@example.invalid',password='LocalOnly!'+crypto.randomBytes(12).toString('hex');
   const r=await config.supabaseAdmin.auth.admin.createUser({email,password,email_confirm:true});assert(!r.error&&r.data.user,'Real GoTrue admin user creation status='+r.error?.status+' code='+r.error?.code+' safeMessage='+String(r.error?.message).replace(/https?:\/\/\S+|[\w.+-]+@[\w.-]+|[A-Za-z0-9_-]{40,}/g,'[omitted]'));actors[key]={id:r.data.user.id,email,password};
   sql(`insert into public.users(id,email,full_name,role,is_active,must_change_password) values(${q(actors[key].id)},${q(email)},'Synthetic Fixture',${q(role)},${active},false);`);
  }
  await login('pic');await login('head');await login('sales');await login('outsider');
  const me=await request('/auth/me','pic');assert.equal(me.status,200);assert.equal(me.json.data.id,actors.pic.id);assert.equal(me.json.data.role,'SA');record('GoTrue login + verified app profile','PASS','Real provider password grant + PostgREST profile; HTTP 200, matching server actor/role');
  const inactive=await request('/auth/login',null,{method:'POST',body:JSON.stringify({email:actors.inactive.email,password:actors.inactive.password})});assert.equal(inactive.status,401);assert(!inactive.json.data?.accessToken);const direct=await config.createSupabaseAuthClient().auth.signInWithPassword({email:actors.inactive.email,password:actors.inactive.password});assert(direct.data.session);const blocked=await fetch(api+'/auth/me',{headers:{Authorization:'Bearer '+direct.data.session.access_token}});assert.equal(blocked.status,401);record('Inactive account','PASS','Real GoTrue can authenticate identity; application login/profile deny inactive public account with HTTP 401');
  const invalid=await fetch(api+'/auth/me',{headers:{Authorization:'Bearer invalid-synthetic-token'}});assert.equal(invalid.status,401);record('Invalid session','PASS','Actual GoTrue rejection propagated as application HTTP 401');
  sql(`insert into public.projects(id,name,customer,scenario_id,sales_id,pic_id,status,selected_document_keys,estimated_revenue)
    select ${q(pid)},'Synthetic Service Project','Synthetic Customer',id,${q(actors.sales.id)},${q(actors.pic.id)},'ACTIVE','["proposal_deck_solusi","assessment"]',100
    from public.scenarios where name='Pra-Tender' and is_active;
    update public.project_phases set status='ACTIVE',pic_id=${q(actors.pic.id)} where project_id=${q(pid)};
    insert into public.project_milestones(id,project_id,workflow_stage_id,name,step_order,status,pic_id,start_date,duration_working_days,due_date)
    select case c.document_key when 'proposal_deck_solusi' then ${q(mid)}::uuid else ${q(otherMid)}::uuid end,${q(pid)},ws.id,'Synthetic Milestone',
      case c.document_key when 'proposal_deck_solusi' then 1 else 2 end,'IN_PROGRESS',${q(actors.pic.id)},current_date-1,2,current_date+1
    from public.output_document_stage_catalog c join public.workflow_stages ws on ws.stage_key=c.stage_key
      join public.scenarios s on s.id=ws.scenario_id and s.name='Pra-Tender' and s.is_active where c.document_key in('proposal_deck_solusi','assessment');
    insert into public.project_output_documents(id,project_id,document_key,milestone_id,title,is_required,is_selected,status)
    select case document_key when 'proposal_deck_solusi' then ${q(oid)}::uuid else gen_random_uuid() end,${q(pid)},document_key,
      case document_key when 'proposal_deck_solusi' then ${q(mid)}::uuid else ${q(otherMid)}::uuid end,'Synthetic Output',is_required,true,'TO_DO'
    from public.output_document_stage_catalog where document_key in('proposal_deck_solusi','assessment');`);
  const store=new Map(),events=new EventTarget();globalThis.window={localStorage:{getItem:k=>store.get(k)??null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)},addEventListener:events.addEventListener.bind(events),removeEventListener:events.removeEventListener.bind(events),dispatchEvent:events.dispatchEvent.bind(events)};
  process.env.NEXT_PUBLIC_API_URL=api;const auth=require(path.join(root,'frontend/src/lib/auth.ts')),client=require(path.join(root,'frontend/src/lib/api-client.ts'));
  const fresh=await login('pic');auth.setAuthTokens(fresh);
  const uploadPath=`/projects/${pid}/output-documents/proposal_deck_solusi/upload`,receipt=crypto.randomUUID();const form=new FormData();form.append('file',new Blob([bytes],{type:'application/pdf'}),'synthetic.pdf');form.append('request_id',receipt);form.append('expected_draft_revision','0');
  process.stdout.write('WAIT: real GoTrue-issued short-lived access token expiry, then concurrent HTTP uploads\n');
  await new Promise(r=>setTimeout(r,31000));const previousRefresh=counts.refresh,startUpload=counts.api['/api'+uploadPath]||0,startProfile=counts.api['/api/auth/me']||0;
  const parallel=await Promise.all([client.apiClient('/auth/me'),client.apiClient(uploadPath,{method:'POST',body:form})]);const receipts=[parallel[1]];
  assert.equal(counts.refresh-previousRefresh,1);assert.equal(counts.api['/api'+uploadPath]-startUpload,2);assert.equal(counts.api['/api/auth/me']-startProfile,2);assert.equal(parallel[0].id,actors.pic.id);receipts.push(await client.apiClient(uploadPath,{method:'POST',body:form}));assert.deepEqual(receipts[0],receipts[1]);tokens.pic={...tokens.pic,...auth.getAuthSession()};
  assert.notEqual(auth.getAuthSession().refreshToken,fresh.refreshToken,'Provider refresh rotates token');
  record('Concurrent 401 / single refresh / at most one replay','PASS','Actual expired profile + multipart requests share one real refresh; each attempted exactly twice; subsequent committed upload retry returns equal receipt');
  assert.equal(sql(`select count(*) from public.project_output_document_files where output_document_id=${q(oid)};`),'1');assert.equal(sql(`select count(*) from storage.objects where bucket_id='workflow-documents';`),'1');record('Upload receipt replay','PASS','Actual app Multer/controller/Storage upload + RPC: Committed upload retry has one registry row and one stored object');
  const file=receipts[0].fileId||receipts[0].file_id;assert(file,'Upload response file ID');
  const downloadPath=`/projects/${pid}/output-documents/proposal_deck_solusi/files/${file}/download`;
  await login('pic');const signed=await request(downloadPath,'pic');assert.equal(signed.status,200);const downloaded=await fetch(signed.json.data.url);assert.equal(downloaded.status,200);assert.deepEqual(Buffer.from(await downloaded.arrayBuffer()),bytes);record('Draft upload / authorized signed download bytes','PASS','Actual app handler + Storage API private object, signed URL HTTP 200, exact byte equality');
  await login('outsider');let signBefore=counts.storageSign;const denied=await request(downloadPath,'outsider');assert([403,404].includes(denied.status));assert(!denied.json.data?.url);assert.equal(counts.storageSign,signBefore);await login('sales');const draftSales=await request(downloadPath,'sales');assert([403,404].includes(draftSales.status));record('Unauthorized / draft privacy','PASS','Outsider and Sales cannot obtain draft URL; unauthorized read triggers no Storage signing operation');
  const submitPath=`/projects/${pid}/output-documents/submit`,submitId=crypto.randomUUID();await login('pic');const submitBody=JSON.stringify({items:[{document_key:'proposal_deck_solusi',expected_draft_revision:receipts[0].draftRevision,request_id:submitId}]});
  const submitted=await request(submitPath,'pic',{method:'POST',body:submitBody});assert.equal(submitted.status,200);assert(submitted.json.data.results?.every(x=>x.success),'Submit batch succeeded');
  const replay=await request(submitPath,'pic',{method:'POST',body:submitBody});assert.equal(replay.status,200);assert(replay.json.data.results?.every(x=>x.success));assert.equal(sql(`select count(*) from public.project_output_document_versions where output_document_id=${q(oid)};`),'1');record('Phase33 API submit and replay','PASS','Real app submit route invokes installed Phase33 RPC; retry leaves exactly one immutable snapshot');
  const version=sql(`select current_version_id from public.project_output_documents where id=${q(oid)};`);await login('head');const reviewed=await request(`/projects/${pid}/output-documents/review`,'head',{method:'POST',body:JSON.stringify({decision:'APPROVE',items:[{document_key:'proposal_deck_solusi',expected_version_id:version,request_id:crypto.randomUUID()}]})});assert.equal(reviewed.status,200);assert(reviewed.json.data.results?.every(x=>x.success));
  await login('sales');const approved=await request(downloadPath+'?version_id='+version,'sales');assert.equal(approved.status,200);const approvedBytes=await fetch(approved.json.data.url);assert.deepEqual(Buffer.from(await approvedBytes.arrayBuffer()),bytes);
  await login('outsider');signBefore=counts.storageSign;const restricted=await request(downloadPath+'?version_id='+version,'outsider');assert([403,404].includes(restricted.status));assert.equal(counts.storageSign,signBefore);record('Approved repository access','PASS','Actual reviewed snapshot: Sales owner gets matching bytes; restricted outsider denied before signing');
  await login('sales');const zip=await fetch(api+`/projects/${pid}/output-documents/download-all`,{headers:{Authorization:'Bearer '+tokens.sales.accessToken}});assert.equal(zip.status,200);assert(zip.headers.get('content-type')?.includes('application/zip'));
  const archive=Buffer.from(await zip.arrayBuffer());
  // Independent standard-library ZIP reader verifies CRC and decompression;
  // the application legitimately uses DEFLATE, so raw-byte searching is invalid.
  const extracted=cp.spawnSync('python',['-c',"import io,sys,zipfile; z=zipfile.ZipFile(io.BytesIO(sys.stdin.buffer.read())); assert z.testzip() is None; names=[n for n in z.namelist() if not n.endswith('/')]; assert len(names)==1; sys.stdout.buffer.write(z.read(names[0]))"],{input:archive});
  assert.equal(extracted.status,0,'Standard-library ZIP integrity/extraction');assert.deepEqual(extracted.stdout,bytes,'ZIP extracted bytes match original');record('Approved ZIP bytes','PASS','Real app ZIP validated with independent Python zipfile CRC/extraction; decompressed bytes exactly match original');
  const storagePath=sql(`select storage_path from public.project_output_document_files where id=${q(file)};`);const removed=await config.supabaseAdmin.storage.from('workflow-documents').remove([storagePath]);assert(!removed.error); // Only exact path of this synthetic object, in owned local stack.
  const missing=await request(downloadPath+'?version_id='+version,'sales');if(missing.status===200){const r=await fetch(missing.json.data.url);assert(r.status>=400);}else assert(missing.status>=400);
  const missingZip=await fetch(api+`/projects/${pid}/output-documents/download-all`,{headers:{Authorization:'Bearer '+tokens.sales.accessToken}});assert(missingZip.status>=400);assert(!missingZip.headers.get('content-type')?.includes('application/zip'));record('Missing object / ZIP fail-safe','PASS','Removed only owned exact synthetic object; single download fails and ZIP returns error rather than partial archive');
  await login('outsider');const oldRefresh=tokens.outsider.refreshToken;const loggedOut=await request('/auth/logout','outsider',{method:'POST'});assert.equal(loggedOut.status,200);const after=await request('/auth/refresh',null,{method:'POST',body:JSON.stringify({refreshToken:oldRefresh})});assert.equal(after.status,401);record('GoTrue logout and refresh revocation','PASS','Actual app logout invokes provider; logged-out refresh token rejected. Access JWT revocation before expiry is not assumed');
 }catch(e){record('integration runner','FAIL',String(e.message).replace(/https?:\/\/\S+/g,'[URL omitted]').slice(0,220));process.exitCode=1;}
 finally{fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(output,JSON.stringify({baseline:'37cdba4',services:{GoTrue:'v2.196.0',PostgREST:'v14.17',Storage:'v1.74.0',PostgreSQL:16},results,counts,scope:'Local real services; reconstructed historical schema prerequisites; Node frontend replay client, not browser AuthProvider lifecycle'},null,2)+'\n');await new Promise(r=>server.close(r));await new Promise(r=>gateway.close(r));}
}
main().catch(()=>{process.stderr.write('Integration harness startup failed; no provider details printed\n');process.exitCode=1;});
