"use client";

import Link from "next/link";
import { useState } from "react";
import { Briefcase, Plus, Search, Pencil, CalendarClock } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { useAuth } from "@/components/auth/auth-provider";
import { useProjects } from "@/hooks/use-projects";
import { ProjectStatus } from "@/types/project";

const statuses: ProjectStatus[] = ["DRAFT", "ACTIVE", "POSTPONED", "COMPLETED", "CANCELLED"];
export default function ProjectsPage() {
  const { user } = useAuth(); const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const [status, setStatus] = useState<ProjectStatus | "ALL">("ALL"); const [scenario, setScenario] = useState("");
  const { data, isLoading, isError } = useProjects({ page, limit: 10, search, status, scenarioId: scenario }); const projects = data?.projects || [];
  return <div className="container space-y-6 py-8"><div className="flex flex-col gap-4 border-b border-border/50 pb-6 sm:flex-row sm:items-center sm:justify-between"><div><div className="mb-1 flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-primary"><Briefcase className="h-4 w-4" />Projects</div><h1 className="text-3xl font-bold tracking-tight">Project Management</h1><p className="mt-1 text-sm text-muted-foreground">Manage customer projects, scenarios, ownership, and status.</p></div>{(user?.role === "SUPER_ADMIN" || user?.role === "SALES") && <Link href="/projects/new"><Button className="gap-2"><Plus className="h-4 w-4" />New Project</Button></Link>}</div>
    <div className="grid gap-3 sm:grid-cols-[1fr_180px]"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input className="pl-9" placeholder="Search project or customer" value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} /></div><select className="h-9 rounded-md border border-input bg-card px-3 text-sm" value={status} onChange={(event) => { setStatus(event.target.value as ProjectStatus | "ALL"); setPage(1); }}><option value="ALL">All statuses</option>{statuses.map((item) => <option key={item}>{item}</option>)}</select></div>
    {isLoading ? <p className="py-12 text-center text-muted-foreground">Loading projects...</p> : isError ? <p className="py-12 text-center text-destructive">Unable to load projects.</p> : projects.length === 0 ? <Card><CardContent className="py-12 text-center text-muted-foreground">No projects found.</CardContent></Card> : <Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b bg-muted/40 text-xs uppercase text-muted-foreground"><tr><th className="px-5 py-4">Project</th><th className="px-5 py-4">Customer</th><th className="px-5 py-4">Scenario</th><th className="px-5 py-4">Sales</th><th className="px-5 py-4">Solution Architect</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Created</th><th className="px-5 py-4" /></tr></thead><tbody className="divide-y divide-border/50">{projects.map((project) => <tr key={project.id} className="hover:bg-muted/20"><td className="px-5 py-4"><Link className="font-medium hover:text-primary" href={`/projects/${project.id}`}>{project.name}</Link></td><td className="px-5 py-4">{project.customer}</td><td className="px-5 py-4">{project.scenario?.name || "-"}</td><td className="px-5 py-4">{project.sales?.fullName || project.sales?.full_name || "-"}</td><td className="px-5 py-4">{project.pic?.fullName || project.pic?.full_name || "-"}</td><td className="px-5 py-4"><Badge variant={project.status === "ACTIVE" ? "success" : project.status === "POSTPONED" ? "warning" : project.status === "CANCELLED" ? "destructive" : "outline"}>{project.status}</Badge></td><td className="px-5 py-4 text-xs text-muted-foreground">{new Date(project.created_at || project.createdAt).toLocaleDateString()}</td><td className="px-5 py-4 text-right"><Link href={`/projects/${project.id}`}><Button variant="ghost" size="icon" title="View project"><Pencil className="h-4 w-4" /></Button></Link></td></tr>)}</tbody></table></div><div className="flex items-center justify-between border-t px-5 py-3 text-xs text-muted-foreground"><span>{data?.pagination.total || 0} projects</span><div className="flex gap-2"><Button size="sm" variant="outline" disabled={page <= 1} onClick={() => setPage(page - 1)}>Previous</Button><Button size="sm" variant="outline" disabled={!data?.pagination.hasNextPage} onClick={() => setPage(page + 1)}>Next</Button></div></div></Card>}
  </div>;
}
