'use strict';
const fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),{spawn}=require('node:child_process');
const pause=ms=>new Promise(r=>setTimeout(r,ms));
class Cdp {
 constructor(socket){this.socket=socket;this.sequence=0;this.pending=new Map();this.listeners=new Map();socket.addEventListener('message',event=>{const m=JSON.parse(event.data);if(m.id){const p=this.pending.get(m.id);if(p){this.pending.delete(m.id);m.error?p.reject(Error(m.error.message)):p.resolve(m.result);}}else for(const listener of this.listeners.get(m.method)||[])Promise.resolve(listener(m.params)).catch(error=>{this.eventError=error;});});}
 send(method,params={}){return new Promise((resolve,reject)=>{const id=++this.sequence;const timer=setTimeout(()=>{this.pending.delete(id);reject(Error('CDP timeout: '+method));},30000);this.pending.set(id,{resolve:value=>{clearTimeout(timer);resolve(value);},reject:error=>{clearTimeout(timer);reject(error);}});this.socket.send(JSON.stringify({id,method,params}));});}
 on(method,listener){if(!this.listeners.has(method))this.listeners.set(method,[]);this.listeners.get(method).push(listener);}
 async evaluate(expression){if(this.eventError)throw this.eventError;const r=await this.send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value;}
 async wait(expression,label,timeout=25000){const start=Date.now();let last;while(Date.now()-start<timeout){try{if(await this.evaluate(`Boolean(${expression})`))return;}catch(e){last=e;}await pause(100);}throw Error('Wait failed: '+label+(last?' - '+last.message:''));}
 async viewport(width,height=1000){await this.send('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:false});await pause(400);}
 async navigate(url){await this.send('Page.navigate',{url});await this.wait("document.readyState==='complete'",'page load');}
 async click(expression){const point=await this.evaluate(`(()=>{const e=(${expression});if(!e)throw Error('Control missing');e.scrollIntoView({block:'center',behavior:'instant'});const r=e.getBoundingClientRect();return {x:r.left+r.width/2,y:r.top+r.height/2}})()`);await this.send('Input.dispatchMouseEvent',{type:'mousePressed',...point,button:'left',clickCount:1});await this.send('Input.dispatchMouseEvent',{type:'mouseReleased',...point,button:'left',clickCount:1});await pause(100);}
 async key(key,code,n,modifiers=0){await this.send('Input.dispatchKeyEvent',{type:'keyDown',key,code,windowsVirtualKeyCode:n,modifiers,...(key==='Enter'?{text:'\r',unmodifiedText:'\r'}:{})});await this.send('Input.dispatchKeyEvent',{type:'keyUp',key,code,windowsVirtualKeyCode:n,modifiers});await pause(50);}
 async screenshot(file){await this.evaluate('document.fonts.ready.then(()=>true)');const m=await this.send('Page.getLayoutMetrics');const image=await this.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true,clip:{x:0,y:0,width:m.cssLayoutViewport.clientWidth,height:Math.min(m.cssContentSize.height,14000),scale:1}});await fs.writeFile(file,Buffer.from(image.data,'base64'));}
}
async function launch(fixture,origin){
 const chrome=process.env.WORKFLOW_TEST_CHROME||'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';await fs.access(chrome);
 const profile=await fs.mkdtemp(path.join(os.tmpdir(),'workflow-browser-fixture-'));const child=spawn(chrome,['--headless=new','--disable-background-networking','--disable-sync','--no-first-run','--no-default-browser-check','--disable-extensions','--disable-component-update','--host-resolver-rules=MAP * ~NOTFOUND, EXCLUDE localhost, EXCLUDE 127.0.0.1',`--user-data-dir=${profile}`,'--remote-debugging-address=127.0.0.1','--remote-debugging-port=0','about:blank'],{windowsHide:true,stdio:'ignore'});
 let cdp,browserSocket;
 async function cleanup(){try{if(browserSocket&&browserSocket.readyState===1){browserSocket.send(JSON.stringify({id:999,method:'Browser.close'}));await pause(400);}else if(child.exitCode===null){child.kill();await pause(400);}}finally{cdp?.socket.close();browserSocket?.close();const resolved=path.resolve(profile);if(path.dirname(resolved)!==path.resolve(os.tmpdir())||!path.basename(resolved).startsWith('workflow-browser-fixture-'))throw Error('Unsafe fixture cleanup path');await fs.rm(resolved,{recursive:true,force:true,maxRetries:5,retryDelay:200});}}
 try{let port;for(let i=0;i<100;i++){try{port=(await fs.readFile(path.join(profile,'DevToolsActivePort'),'utf8')).split('\n')[0];break;}catch{await pause(100);}}if(!port)throw Error('Chrome DevTools did not initialize');const version=await(await fetch(`http://127.0.0.1:${port}/json/version`)).json();browserSocket=new WebSocket(version.webSocketDebuggerUrl);await new Promise(r=>browserSocket.addEventListener('open',r,{once:true}));const tabs=await(await fetch(`http://127.0.0.1:${port}/json/list`)).json();const socket=new WebSocket(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(r=>socket.addEventListener('open',r,{once:true}));cdp=new Cdp(socket);const traffic={api:[],blocked:[],allowed:[],errors:[]};
 cdp.on('Fetch.requestPaused',async event=>{const {requestId,request}=event;const u=new URL(request.url);if(!['http:','https:'].includes(u.protocol)){await cdp.send('Fetch.continueRequest',{requestId});return;}
 const api=u.pathname.startsWith('/api/')||['/auth/','/dashboard','/documents','/notifications','/me/'].some(p=>u.pathname.startsWith(p))&&u.origin!==origin;
 if(api){const result=fixture.respond(request.url,request.method,request.postData);traffic.api.push({path:u.pathname,method:request.method,status:result.status,role:fixture.state.role,account:fixture.state.account});if(result.delay)await pause(result.delay);const headers=[{name:'Content-Type',value:'application/json'},{name:'Access-Control-Allow-Origin',value:origin},{name:'Access-Control-Allow-Credentials',value:'true'},{name:'Access-Control-Allow-Headers',value:'*'},{name:'Access-Control-Allow-Methods',value:'GET,POST,PUT,PATCH,DELETE,OPTIONS'},{name:'Cache-Control',value:'no-store'}];await cdp.send('Fetch.fulfillRequest',{requestId,responseCode:result.status,responseHeaders:headers,body:result.body?Buffer.from(JSON.stringify(result.body)).toString('base64'):''});return;}
 if(u.origin===origin){traffic.allowed.push({path:u.pathname,method:request.method});await cdp.send('Fetch.continueRequest',{requestId});return;}
 traffic.blocked.push({host:u.hostname,path:u.pathname});await cdp.send('Fetch.failRequest',{requestId,errorReason:'BlockedByClient'});
 });
 cdp.on('Runtime.exceptionThrown',e=>traffic.errors.push(e.exceptionDetails.exception?.description||e.exceptionDetails.text));await cdp.send('Page.enable');await cdp.send('Runtime.enable');await cdp.send('Network.enable');await cdp.send('Network.setBypassServiceWorker',{bypass:true});await cdp.send('Fetch.enable',{patterns:[{urlPattern:'*',requestStage:'Request'}]});await cdp.send('Emulation.setFocusEmulationEnabled',{enabled:true});return {cdp,traffic,cleanup,browser:version.Browser};}catch(e){await cleanup();throw e;}
}
module.exports={launch,pause};
