'use strict';
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const {createFixture}=require('./fixtures.cjs');const {launch,pause}=require('./cdp.cjs');
const origin=process.env.WORKFLOW_TEST_ORIGIN||'http://127.0.0.1:3000';
if(!['127.0.0.1','localhost'].includes(new URL(origin).hostname))throw Error('Only a loopback frontend is allowed');
const output=path.resolve(process.env.WORKFLOW_TEST_OUTPUT||path.join(__dirname,'../../../docs/dashboard-browser-verification'));
async function main(){await fs.mkdir(output,{recursive:true});const fixture=createFixture();const runtime=await launch(fixture,origin);const {cdp,traffic}=runtime;const results=[];const record=(area,data)=>{results.push({area,...data});console.log(JSON.stringify({area,...data}));};const recent="document.querySelector('section[aria-labelledby=\"recent-activity-heading\"]')";const button=(index)=>`${recent}.querySelectorAll('nav button')[${index}]`;
 const login=async role=>{fixture.state.role=role;fixture.state.locale='en';await cdp.navigate(origin+'/login');await cdp.wait("document.querySelector('#email')&&document.querySelector('#password')",'login form');await cdp.evaluate(`(()=>{for(const [selector,value] of [['#email',${JSON.stringify(role.toLowerCase()+'@fixture.invalid')}],['#password','SyntheticOnly!123']]){const e=document.querySelector(selector);Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(e,value);e.dispatchEvent(new Event('input',{bubbles:true}));}})()`);await cdp.click("document.querySelector('form button[type=submit]')");await cdp.wait("document.querySelector('#dashboard-summary-heading') && document.querySelector('#dashboard-recent-activity-list')",'authenticated dashboard');await cdp.wait("document.querySelector('#dashboard-recent-activity-list').children.length===8",'8 activities');};
 const locale=async value=>{await cdp.evaluate(`(()=>{const s=document.querySelector('select[aria-label]');if(!s)throw Error('Language select missing');s.value=${JSON.stringify(value)};s.dispatchEvent(new Event('change',{bubbles:true}));})()`);await cdp.wait(`document.documentElement.lang===${JSON.stringify(value)}`,'locale');};
 const inspect=async label=>{const m=await cdp.evaluate(`(()=>{const heading=document.querySelector('#dashboard-summary-heading'),grid=heading?.parentElement.querySelector('dl');return {width:innerWidth,clientWidth:document.documentElement.clientWidth,scrollWidth:document.documentElement.scrollWidth,summaryColumns:grid?getComputedStyle(grid).gridTemplateColumns.split(' ').length:null,activityCount:document.querySelector('#dashboard-recent-activity-list')?.children.length??0,workspaceLinks:[...document.querySelectorAll('main a[href*="#milestone-outputs-"]')].map(a=>a.getAttribute('href')),summary:[...document.querySelectorAll('#dashboard-summary-heading ~ dl .tabular-nums')].map(e=>{const r=document.createRange();r.selectNodeContents(e);const card=e.closest('.dashboard-surface').getBoundingClientRect();return {text:e.textContent,fits:[...r.getClientRects()].every(x=>x.left>=card.left-.5&&x.right<=card.right+.5),width:e.clientWidth,scrollWidth:e.scrollWidth}}),alerts:[...document.querySelectorAll('main [role=alert]')].map(e=>e.textContent)}})()`);assert(m.scrollWidth<=m.clientWidth,`${label}: page overflow ${JSON.stringify(m)}`);assert(m.summary.every(x=>x.fits&&x.scrollWidth<=x.width),label+': metric text exceeds card');return m;};
 const shot=async name=>{await cdp.screenshot(path.join(output,name+'.png'));};
 const logout=async()=>{await cdp.click("document.querySelector('button[aria-label=\"Sign out\"],button[aria-label=\"Log out\"],button[aria-label=\"Logout\"],button[aria-label=\"Keluar\"]')");await cdp.wait("document.querySelector('#email')",'logout');};
 try{
 for(const role of (process.env.WORKFLOW_TEST_ROLES||'SALES,HEAD_SA,SA,SUPER_ADMIN').split(',')){
  fixture.state.empty=false;await login(role);
  for(const lang of ['en','id']){await locale(lang);for(const width of [360,390,1440]){await cdp.viewport(width);await pause(200);const m=await inspect(role+' '+lang+' '+width);assert.equal(m.activityCount,8);assert.equal(m.summaryColumns,width<640?1:4);if(['SA','HEAD_SA'].includes(role))assert(m.workspaceLinks.includes(`/projects/${fixture.pid}#milestone-outputs-${fixture.mid}`),'Output workspace must remain linked');await shot(`dashboard-${role.toLowerCase()}-${lang}-${width}`);record('dashboard',{role,locale:lang,viewport:width,...m});}}
  await locale('en');await cdp.viewport(360);
  await cdp.evaluate("document.querySelector('button[aria-controls=\"mobile-navigation\"]').focus()");await cdp.key('Enter','Enter',13);await cdp.wait("document.querySelector('#mobile-navigation').getAttribute('aria-hidden')==='false'",'drawer open');const drawer=await cdp.evaluate(`(()=>{const d=document.querySelector('#mobile-navigation');return {focusInside:d.contains(document.activeElement),overflow:document.body.style.overflow,links:[...d.querySelectorAll('a')].map(a=>a.getAttribute('href'))}})()`);assert(drawer.focusInside&&drawer.overflow==='hidden');assert(drawer.links.includes('/projects')&&drawer.links.includes('/documents'));assert.equal(drawer.links.includes('/approvals'),['HEAD_SA','SUPER_ADMIN'].includes(role));await shot(`drawer-${role.toLowerCase()}-360`);await cdp.evaluate(`(()=>{const d=document.querySelector('#mobile-navigation'),a=[...d.querySelectorAll('a[href],button:not([disabled]),input:not([disabled]),select:not([disabled]),[tabindex]:not([tabindex="-1"])')].filter(e=>e.getClientRects().length);a.at(-1).focus()})()`);await cdp.key('Tab','Tab',9);assert(await cdp.evaluate("document.querySelector('#mobile-navigation').contains(document.activeElement)"));await cdp.key('Escape','Escape',27);await cdp.wait("document.querySelector('#mobile-navigation').getAttribute('aria-hidden')==='true'",'drawer Escape');assert(await cdp.evaluate("document.activeElement.getAttribute('aria-controls')==='mobile-navigation'&&document.body.style.overflow!=='hidden'"));record('drawer',{role,viewport:360,focus:true,escape:true,scrollRestored:true,links:drawer.links});
  // Actual cursor API and real client component state, including loading/failure/retry.
  fixture.state.activityDelay=700;await cdp.click(button(1));await cdp.wait(`${button(1)}.disabled`,'activity loading');await cdp.wait("document.querySelector('#dashboard-recent-activity-list')?.textContent.includes('activity 09')",'activity page 2');assert.equal(await cdp.evaluate("document.querySelector('#dashboard-recent-activity-list').children.length"),8);await locale('id');assert(await cdp.evaluate(`${recent}.querySelector('nav').textContent.includes('Halaman 2')`));await cdp.click(button(1));await cdp.wait("document.querySelector('#dashboard-recent-activity-list')?.textContent.includes('activity 17')",'activity page 3');assert.equal(await cdp.evaluate("document.querySelector('#dashboard-recent-activity-list').children.length"),1);assert(await cdp.evaluate(`${button(1)}.disabled`));await shot(`activity-last-${role.toLowerCase()}-360`);await cdp.click(button(0));await cdp.wait("document.querySelector('#dashboard-recent-activity-list')?.textContent.includes('activity 09')",'previous page 2');await cdp.click(button(0));await cdp.wait("document.querySelector('#dashboard-recent-activity-list')?.textContent.includes('activity 01')",'previous page 1');assert(await cdp.evaluate(`${button(0)}.disabled`));record('activity',{role,items:[8,8,1],nextPrevious:true,localeRetainsPage:true,lastNextDisabled:true,firstPreviousDisabled:true,loading:true});fixture.state.activityDelay=0;
  // Existing route pages; no writes or downloads are exercised.
  for(const route of ['/projects',`/projects/${fixture.pid}`,'/documents','/approvals']){await cdp.navigate(origin+route);await cdp.wait("document.querySelector('main') && document.querySelector('main').textContent.length>20",route);await pause(550);for(const width of [360,390,1440]){await cdp.viewport(width);await pause(100);const m=await inspect(role+' '+route+' '+width);await shot(`page-${role.toLowerCase()}-${route.startsWith('/projects/')?'detail':route.slice(1)}-${width}`);record('route',{role,route,locale:'id',viewport:width,...m});}}
  await cdp.navigate(origin+'/');await cdp.wait("document.querySelector('#dashboard-recent-activity-list')",'return dashboard');await locale('en');fixture.state.empty=true;await cdp.navigate(origin+'/?fixture-empty=1');await cdp.wait("document.querySelector('#dashboard-summary-heading')",'empty dashboard');await pause(500);await cdp.viewport(360);const empty=await inspect(role+' empty');assert.equal(empty.activityCount,0);await shot(`empty-${role.toLowerCase()}-360`);record('empty',{role,viewport:360,locale:'en',...empty});fixture.state.empty=false;await logout();
 }
 record('isolation',{unconfigured:fixture.state.unknown,apiRequests:traffic.api.length,blockedExternal:traffic.blocked.length,nonUiNetworkRequestsForwarded:0});assert.deepEqual(fixture.state.unknown,[],'Unconfigured API request must be fixed explicitly');
 }catch(error){record('failure',{message:error.message,ui:await cdp.evaluate("({url:location.pathname,buttons:[...document.querySelectorAll('button[aria-controls]')].map(e=>({label:e.getAttribute('aria-label'),controls:e.getAttribute('aria-controls'),expanded:e.getAttribute('aria-expanded'),rect:e.getBoundingClientRect().toJSON()})),drawerHidden:document.querySelector('#mobile-navigation')?.getAttribute('aria-hidden'),alerts:[...document.querySelectorAll('[role=alert]')].map(e=>e.textContent)})")});await shot('failure');throw error;}finally{await fs.writeFile(path.join(output,'results.json'),JSON.stringify({baseline:'e25cd05',browser:runtime.browser,fixture:'Synthetic login/API; actual app/AuthProvider/app shell; backend auth and GoTrue/Storage not tested',results,traffic,unknown:fixture.state.unknown},null,2)+'\n');await runtime.cleanup();}
}
main().catch(error=>{console.error(error.stack);process.exitCode=1;});
