'use strict';
// Synthetic API contracts only. No credentials, URLs or data from live services.
const uuid = n => `90000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const pid=uuid(1),mid=uuid(2),phase=uuid(3),sid=uuid(4),now='2026-10-08T12:00:00.000Z';
function createFixture(){
 const state={role:'SALES',account:1,locale:'en',empty:false,activityFailure:false,activityDelay:0,requests:[],unknown:[]};
 const user=role=>({id:uuid(({SALES:10,SA:11,HEAD_SA:12,SUPER_ADMIN:13})[role]+state.account*100),fullName:`Fixture ${role} ${state.account}`,full_name:`Fixture ${role} ${state.account}`,role,email:`${role.toLowerCase()}-${state.account}@fixture.invalid`,isActive:true,is_active:true,mustChangePassword:false,preferredLanguage:state.locale});
 const scenario={id:sid,name:'Pra-Tender',workflow_model:'OPERATIONAL_V2',workflow_version:2};
 const project=(n,status='ACTIVE',currentRole='SA')=>({id:n===1?pid:uuid(n+20),name:n===1?'Fixture solution assessment and enterprise integration with a long project name':`Fixture ${status} project`,customer:'Synthetic customer',clientName:'Synthetic customer',projectCode:`FIX-${n}`,sales_id:user('SALES').id,pic_id:user('SA').id,sales:user('SALES'),pic:user('SA'),scenario_id:sid,current_scenario_id:sid,active_phase_id:phase,phase_migration_state:'READY',scenario,active_scenario:scenario,phases:[{id:phase,project_id:pid,scenario_id:sid,phase_key:'PRA_TENDER',status:'ACTIVE',selected_document_keys:['proposal_deck_solusi']}],status,is_postponed:false,estimated_revenue:n===1?25000000:0,estimated_revenue_exact:n===1?'25000000':'0',currentRole,currentStage:'Solution Assessment',pic_revision:'0',currentMilestone:{id:mid,name:'Solution Assessment',step_order:1,status:'IN_PROGRESS',default_role:'SA',start_date:'2026-10-01',due_date:'2026-10-30'},createdAt:now,updatedAt:now,created_at:now,updated_at:now,selected_document_keys:['proposal_deck_solusi'],totalMilestones:1,completedMilestones:0});
 const projects=()=>state.empty?[]:[project(1),project(2,'DRAFT','SALES'),project(3,'WAITING_RESULT','SALES'),project(4,'DRAFT','HEAD_SA')];
 const milestones=()=>[{id:mid,project_id:pid,phase_id:phase,workflow_stage_id:uuid(5),name:'Solution Assessment',description:'Synthetic active milestone',step_order:1,status:'IN_PROGRESS',pic_id:user('SA').id,pic:user('SA'),workflow_stage:{id:uuid(5),default_role:'SA',stage_key:'PROPOSAL_SOLUTION'},start_date:'2026-10-01',due_date:'2026-10-30',duration_working_days:22,created_at:now,updated_at:now,project:{id:pid,name:project(1).name,customer:'Synthetic customer',status:'ACTIVE',is_postponed:false}}];
 const activities=()=>state.empty?[]:Array.from({length:17},(_,i)=>({id:uuid(200+i),action:'PROJECT_CREATED',entityType:'ACTIVITY_LOG',details:`Synthetic activity ${String(i+1).padStart(2,'0')}`,createdAt:new Date(Date.parse(now)-i*60000).toISOString(),user:user(state.role),project:{id:pid,name:`Fixture activity ${String(i+1).padStart(2,'0')} - account ${state.account}`,projectCode:'FIX-1'}}));
 const approval=()=>({id:'output:'+uuid(7),category:'OUTPUT_DOCUMENT',status:'PENDING',isCurrentApproval:true,projectId:pid,projectName:project(1).name,projectCode:'FIX-1',clientName:'Synthetic customer',title:'Proposal/Deck Solusi',documentKey:'proposal_deck_solusi',milestoneName:'Solution Assessment',milestoneId:mid,phaseName:'Pra-Tender',outputId:uuid(7),snapshotId:uuid(8),versionNumber:1,fileCount:2,submittedBy:'Fixture SA',submittedAt:now,requestedAt:now,canReview:true,reviewBlockedReason:null});
 const output=()=>({id:uuid(7),projectId:pid,key:'proposal_deck_solusi',milestoneId:mid,name:'Proposal/Deck Solusi',group:'PRA_TENDER',isRequired:true,isSelected:true,status:state.role==='SA'?'REVISION_REQUIRED':'IN_REVIEW',currentVersionId:uuid(8),currentVersionNumber:1,versionCount:1,draftRevision:1,files:[{id:uuid(9),fileName:'Synthetic_solution_proposal_with_a_long_filename.pdf',fileSize:2048,mimeType:'application/pdf'}],draftFiles:[],reviewFeedback:'Please revise the synthetic architecture description.',fileRevisions:[]});
 const dashboard=()=>({summary:{totalProjects:projects().length,activeProjects:state.empty?0:1,completedProjects:0,onHoldProjects:0,overdueMilestones:0,waitingApproval:state.empty?0:1},scenarioDistribution:[],statusDistribution:[],projectProgress:projects().map(p=>({id:p.id,name:p.name,projectCode:p.projectCode,clientName:p.customer,status:p.status,percentage:p.status==='ACTIVE'?50:0,progress:50,targetEndDate:'2026-10-30',totalMilestones:2,completedMilestones:1,overdueMilestones:0})),recentActivity:activities().slice(0,8),recentActivityPagination:{pageSize:8,nextCursor:state.empty?null:'fixture-cursor-8'},outputDocuments:{reviewQueue:!state.empty&&state.role==='HEAD_SA'?[{projectId:pid,milestoneId:mid,projectName:project(1).name,count:1}]:[],revisionQueue:!state.empty&&state.role==='SA'?[{projectId:pid,milestoneId:mid,projectName:project(1).name,count:1}]:[],salesProgress:state.empty?[]:[{projectId:pid,approvedCount:1,selectedCount:2}]},saWorkload:!state.empty&&state.role==='HEAD_SA'?[{saId:user('SA').id,saName:user('SA').fullName,activeProjectCount:1,activeMilestoneCount:1,overdueCount:0,revisionCount:1,waitingReviewCount:1,nearestDeadline:'2026-10-30'}]:[],headSaProjectValues:state.role==='HEAD_SA'?{active:{count:state.empty?0:1,estimatedRevenue:state.empty?0:25000000},won:{count:0,finalContractValue:0}}:null,salesResults:null,allWorkStatus:{total:projects().length,planning:state.empty?0:2,active:state.empty?0:1,postponed:0,completed:0,won:0,lost:0,waitingResult:state.empty?0:1,cancelled:0},phaseWorkStatus:{PRA_TENDER:{active:state.empty?0:1,postponed:0},ON_SUBMISSION_TENDER:{won:0,lost:0}}});
 function respond(url,method,body=''){
  const u=new URL(url),p=u.pathname.replace(/^\/api(?=\/)/,'');state.requests.push({path:p,method,role:state.role,account:state.account});const ok=data=>({status:200,body:{success:true,data,message:'Synthetic fixture'}});
  if(method==='OPTIONS')return {status:204,body:null};
  if(p==='/auth/login'&&method==='POST'){const data=JSON.parse(body);const role=data.email.split('@')[0].split('-')[0].toUpperCase();if(!['SALES','SA','HEAD_SA','SUPER_ADMIN'].includes(role))throw Error('Invalid fixture login');state.role=role;return ok({user:user(role),accessToken:`fixture-only-${role}-${state.account}`,refreshToken:'fixture-only-refresh'});}
  if(p==='/auth/logout'&&method==='POST')return ok({});
  if(p==='/auth/me'&&method==='GET')return ok(user(state.role));
  if(p==='/auth/preferences/language'&&method==='GET')return ok({language:state.locale});
  if(p==='/auth/preferences/language'&&method==='PUT'){state.locale=JSON.parse(body).language;return ok({language:state.locale});}
  if(method!=='GET'){state.unknown.push({path:p,method});return {status:501,body:{success:false,message:'Unconfigured fixture mutation',errors:{code:'FIXTURE_UNHANDLED'}}};}
  if(p==='/dashboard')return ok(dashboard());
  if(p==='/dashboard/activity'){const offset=u.searchParams.get('cursor')==='fixture-cursor-16'?16:8;const a=activities();if(state.activityFailure)return {status:503,delay:state.activityDelay,body:{success:false,message:'Synthetic temporary activity failure'}};return {...ok({items:a.slice(offset,offset+8),pageSize:8,nextCursor:a.length>offset+8?'fixture-cursor-'+(offset+8):null}),delay:state.activityDelay};}
  if(p==='/projects'){let list=projects();if(u.searchParams.has('status'))list=list.filter(x=>x.status===u.searchParams.get('status'));return ok({projects:list,pagination:{page:1,limit:100,total:list.length,totalPages:1,hasNextPage:false,hasPrevPage:false}});}
  if(p==='/scenarios')return ok([scenario]);
  if(p==='/users/solution-architects')return ok([user('SA')]);
  if(p==='/me/assigned-milestones')return ok(state.empty?[]:milestones());
  if(p==='/approvals/overview')return ['HEAD_SA','SUPER_ADMIN'].includes(state.role)?ok({stats:{totalPending:state.empty?0:1,pendingDocs:state.empty?0:1,pendingProjectPlans:0,pendingDeadlines:0},items:state.empty?[]:[approval()]}):{status:403,body:{success:false,message:'Fixture role restriction'}};
  if(p==='/notifications/unread-count')return ok({unreadCount:0});
  if(p==='/notifications')return ok([]);
  if(p==='/documents')return ok(state.empty?[]:[{id:uuid(30),projectId:pid,title:'Synthetic approved assessment report',category:'ASSESSMENT_REPORT',status:'APPROVED',canReadProject:true,canManageAccess:['HEAD_SA','SUPER_ADMIN'].includes(state.role),accessMode:'RESTRICTED',canUploadVersion:false,createdAt:now,updatedAt:now,project:{id:pid,name:project(1).name,projectCode:'FIX-1',clientName:'Synthetic customer'},versions:[{id:uuid(31),versionNumber:1,fileName:'synthetic-assessment.pdf',fileSize:1024,mimeType:'application/pdf',status:'APPROVED',isLatest:true,createdAt:now}]}]);
  if(p==='/documents/outputs')return ok([]);
  if(p===`/projects/${pid}`)return ok(project(1));
  if(p===`/projects/${pid}/milestones`)return ok(milestones());
  if(p===`/projects/${pid}/output-documents`)return ok({documents:['SALES','SUPER_ADMIN'].includes(state.role)?[]:[output()],canUpload:state.role==='SA',canReview:state.role==='HEAD_SA',canSelect:false,summary:{total:1,required:1,selected:1,approved:0,inReview:state.role==='SA'?0:1,revisionRequired:state.role==='SA'?1:0}});
  if(p===`/projects/${pid}/plan-approval`)return ok({id:uuid(40),project_id:pid,phase_id:phase,status:'APPROVED',submitted_at:now,reviewed_at:now,request_note:null,review_note:null,requested_by:user('SALES'),reviewed_by:user('HEAD_SA')});
  if(p===`/projects/${pid}/assignments`||p===`/projects/${pid}/intake-attachments`||p===`/projects/${pid}/plan-approval-history`)return ok([]);
  if(p===`/projects/${pid}/activities`)return ok({items:activities().slice(0,8).map(a=>({id:a.id,action:a.action,description:a.details,createdAt:a.createdAt,actor:{id:a.user.id,name:a.user.fullName,role:a.user.role}})),nextCursor:null});
  if(p===`/projects/${pid}/document-sharing`)return ok({mode:'RESTRICTED',revision:0,updatedAt:null,updatedBy:null});
  if(p===`/milestones/${mid}/deadline-status`)return ok({milestone_id:mid,due_date:'2026-10-30',deadline_status:'ON_TRACK',remaining_working_days:16});
  if(p===`/milestones/${mid}/deadline-approval`)return ok(null);
  if(p===`/milestones/${mid}/contributions`)return ok([]);
  state.unknown.push({path:p,method});return {status:501,body:{success:false,message:'Unconfigured fixture API',errors:{code:'FIXTURE_UNHANDLED'}}};
 }
 return {state,respond,pid,mid,user};
}
module.exports={createFixture};
