import { strict as assert } from 'assert';
import React from 'react';
import { isValidElement, type ReactNode } from 'react';
import * as language from '../components/i18n/language-provider';
import { QueryClient } from '@tanstack/react-query';
import * as auth from '../components/auth/auth-provider';
import * as api from './api-client';
import { useBusinessRequest } from '../hooks/use-business-request';
import { projectKeys } from './query-keys';
import * as outputHooks from '../hooks/use-output-documents';
import { BusinessConfirmation } from '../components/projects/business-confirmation';
import { OutputDocumentFiles } from '../components/projects/output-document-files';
import { Button } from '../components/ui/button';
import { createBusinessRequestStore } from './business-request';
import { formatBusinessAuditValue,formatBusinessAudit } from './activity-timeline';
import { en } from '../i18n/en';import { id } from '../i18n/id';
import { setActiveLanguage, translate } from '../i18n';
import type { ProjectOutputDocumentItem } from '../types/project';

type Element=React.ReactElement<any>;
function elements(node:ReactNode):Element[]{if(Array.isArray(node))return node.flatMap(elements);if(!isValidElement(node))return [];return [node as Element,...elements((node as Element).props.children)];}
const flush=()=>new Promise<void>(resolve=>setImmediate(resolve));
async function run(){
  assert.deepEqual(Object.keys(en.businessAudit).sort(),Object.keys(id.businessAudit).sort());
  assert.deepEqual(Object.keys(en.businessAuditFields).sort(),Object.keys(id.businessAuditFields).sort());
  for(const key of Object.keys(en.businessAudit) as Array<keyof typeof en.businessAudit>)assert.deepEqual(en.businessAudit[key].match(/\{\w+\}/g)||[],id.businessAudit[key].match(/\{\w+\}/g)||[]);
  for(const locale of ['en','id'] as const){setActiveLanguage(locale);assert(!translate('businessAudit.files',{count:2}).includes('{'));assert.notEqual(formatBusinessAuditValue('status','PENDING'),translate('common.notAvailable'));assert.notEqual(formatBusinessAuditValue('status','IN_PROGRESS'),translate('common.notAvailable'));assert.notEqual(formatBusinessAuditValue('status','REJECTED'),translate('common.notAvailable'));assert(formatBusinessAuditValue('start_date','2026-10-07').includes('7'));assert(formatBusinessAudit({objectType:'PROJECT',objectId:'p',changedFields:['final_contract_value'],before:{final_contract_value:'100.00'},after:{final_contract_value:'250.00'}}).includes('250'));}
  setActiveLanguage('en'); const oldZone=process.env.TZ;process.env.TZ='America/Los_Angeles';assert.equal(formatBusinessAuditValue('due_date','2026-10-07'),'Oct 7, 2026');process.env.TZ=oldZone;
  const store=createBusinessRequestStore();let resolve!:()=>void;let reads=0,calls=0;const headers:Record<string,string>[]=[];
  const read=async()=>{reads++;return '2026-10-07T00:00:00.000Z';};
  const send=async(h:Record<string,string>)=>{calls++;headers.push(h);await new Promise<void>(r=>resolve=r);return 1;};
  const first=store.run('p','TIMELINE',{date:'2026-10-07'},read,send,()=>{});
  const concurrent=store.run('p','TIMELINE',{date:'2026-10-07'},read,send,()=>{});
  await flush();assert.equal(calls,1);resolve();assert.deepEqual(await Promise.all([first,concurrent]),[1,1]);assert.equal(reads,1);
  const failing=async(h:Record<string,string>)=>{headers.push(h);throw new Error('network');};
  await assert.rejects(()=>store.run('p','POSTPONE',{reason:'x'},read,failing,()=>{}));
  const failedId=headers.at(-1)!['x-business-request-id'];
  await store.run('p','POSTPONE',{reason:'x'},read,async h=>{assert.equal(h['x-business-request-id'],failedId);return 1;},()=>{});
  let refreshed=0;await assert.rejects(()=>store.run('p','INFO',{name:'new'},read,async()=>{throw {status:409};},()=>{refreshed++;}));assert.equal(refreshed,1);
  let timestampAttempts=0;await assert.rejects(()=>store.run("p","INFO",{},async()=>{timestampAttempts++;throw new Error("unavailable");},async()=>1,()=>{}));
  await store.run("p","INFO",{},async()=>{timestampAttempts++;return "2026-10-07T00:00:00Z";},async()=>1,()=>{});assert.equal(timestampAttempts,2,"Failed timestamp read does not strand the running request");

  const originals={state:React.useState,ref:React.useRef,effect:React.useEffect,context:React.useContext,auth:auth.useAuth,api:api.apiClient,language:language.useLanguage,upload:outputHooks.useUploadOutputDocument,remove:outputHooks.useRemoveOutputDocumentFile,download:outputHooks.useOutputDocumentFileDownload};
  let states:any[]=[],refs:any[]=[],si=0,ri=0;
  (React as any).useState=(initial:any)=>{const i=si++;if(!(i in states))states[i]=typeof initial==='function'?initial():initial;return [states[i],(next:any)=>states[i]=typeof next==='function'?next(states[i]):next];};
  (React as any).useRef=(initial:any)=>refs[ri++]??={current:initial};
  (React as any).useEffect=()=>{};(language as any).useLanguage=()=>({});
  const render=(component:()=>Element)=>{si=0;ri=0;return component();};
  try{
    let writes=0,open=true,fail=true;
    const confirmationProps={open:true,onOpenChange:(value:boolean)=>{open=value;},title:'Project / Output',changes:['old.pdf -> new.pdf'],action:'Save files',onConfirm:async()=>{writes++;if(fail)throw new Error('offline');}};
    const tree=()=>render(()=>BusinessConfirmation(confirmationProps));
    const button=(label:string)=>elements(tree()).find(item=>item.type===Button&&item.props.children===label)!;
    setActiveLanguage('en');assert.equal(writes,0);button(translate('common.cancel')).props.onClick();assert.equal(writes,0);assert.equal(open,false);
    open=true;button('Save files').props.onClick();await flush();assert.equal(writes,1);assert.equal(open,true);assert(elements(tree()).some(item=>item.props.role==='alert'));
    setActiveLanguage('id');assert(elements(tree()).some(item=>item.props.role==='alert'&&item.props.children===translate('businessAudit.failed')));
    fail=false;button('Save files').props.onClick();await flush();assert.equal(writes,2);assert.equal(open,false);
    states=[];refs=[];let releaseDecision!:()=>void;open=true;
    confirmationProps.onConfirm=async()=>{writes++;await new Promise<void>(resolve=>releaseDecision=resolve);};
    const saveOnce=button('Save files').props.onClick;saveOnce();saveOnce();assert.equal(writes,3,'Click latch permits only one mutation');
    releaseDecision();await flush();assert.equal(open,false);
    states=[];refs=[];open=true;confirmationProps.onConfirm=async()=>{writes++;throw {status:409};};
    button('Save files').props.onClick();await flush();assert.equal(open,true);assert.equal(button('Save files').props.disabled,true);
    button('Save files').props.onClick();assert.equal(writes,4,'Stale confirmation cannot overwrite automatically');
    states=[];refs=[];let uploadCalls=0,removeCalls=0;
    (outputHooks as any).useUploadOutputDocument=()=>({mutateAsync:async()=>{uploadCalls++;return {draftRevision:1};}});
    (outputHooks as any).useRemoveOutputDocumentFile=()=>({mutateAsync:async()=>{removeCalls++;return {draftRevision:2};}});
    (outputHooks as any).useOutputDocumentFileDownload=()=>({mutateAsync:async()=>({})});
    const doc={key:'proposal_teknis',name:'Proposal',status:'DRAFT',draftRevision:0,draftFiles:[],files:[]} as unknown as ProjectOutputDocumentItem;
    const props={projectId:'p',document:doc,editable:true,blocked:false,onBusyChange:()=>{},refreshDraft:async()=>doc};
    const draftTree=()=>render(()=>OutputDocumentFiles(props));
    const selected={name:'one.pdf',size:1,type:'application/pdf'} as File;
    elements(draftTree()).find(item=>item.type==='input')!.props.onChange({target:{files:[selected],value:'selected'}});
    assert.equal(uploadCalls,0,'Choosing files must not write');
    const dialog=()=>elements(draftTree()).find(item=>item.type===BusinessConfirmation)!;
    assert.equal(dialog().props.open,true);dialog().props.onOpenChange(false);assert.equal(uploadCalls,0);
    assert(elements(draftTree()).some(item=>item.props.children==='one.pdf'),'Cancel retains selected file');
    setActiveLanguage('en');assert(elements(draftTree()).some(item=>item.props.children==='one.pdf'),'Locale does not reset selected files');
    assert.equal(removeCalls,0);
    states=[];refs=[];
    const client=new QueryClient();
    (React as any).useContext=()=>client;(auth as any).useAuth=()=>({user:{id:'owner'}});
    const sent:Record<string,string>[]=[];
    (api as any).apiClient=async(_path:string,options:any)=>{sent.push(options.headers);return {};};
    client.setQueryData(projectKeys.detailWithoutActivity('p'),{updated_at:'2026-10-07T00:00:00.000Z'});
    si=0;ri=0;const request=useBusinessRequest();request.prepare('p');
    client.setQueryData(projectKeys.detailWithoutActivity('p'),{updated_at:'2026-10-07T01:00:00.000Z'});
    await request('p','INFO','/projects/p','PATCH',{name:'Changed'});
    assert.equal(sent[0]['x-business-expected-updated-at'],'2026-10-07T00:00:00.000Z','Editing snapshot survives query refresh');
    let account='owner';(auth as any).useAuth=()=>({user:{id:account}});
    (api as any).apiClient=async(_path:string,options:any)=>{sent.push(options.headers);throw new Error('offline');};
    si=0;ri=0;const firstAccount=useBusinessRequest();await assert.rejects(()=>firstAccount('p','INFO','/projects/p','PATCH',{name:'Pending'}));
    const firstReceipt=sent.at(-1)!['x-business-request-id'];account='different';
    si=0;ri=0;const secondAccount=useBusinessRequest();await assert.rejects(()=>secondAccount('p','INFO','/projects/p','PATCH',{name:'Pending'}));
    assert.notEqual(sent.at(-1)!['x-business-request-id'],firstReceipt,'Accounts do not share pending business intents');
    client.clear();
  }finally{(React as any).useState=originals.state;(React as any).useRef=originals.ref;(React as any).useEffect=originals.effect;(React as any).useContext=originals.context;(auth as any).useAuth=originals.auth;(api as any).apiClient=originals.api;(language as any).useLanguage=originals.language;(outputHooks as any).useUploadOutputDocument=originals.upload;(outputHooks as any).useRemoveOutputDocumentFile=originals.remove;(outputHooks as any).useOutputDocumentFileDownload=originals.download;setActiveLanguage('en');}
  console.log('Business confirmation, cancel/failure/retry/locale, queued file selection, stable concurrent request and date/i18n tests passed.');
}
run().catch(error=>{console.error(error);process.exitCode=1;});
